import 'dart:async';
import 'package:feda_flutter/src/exports/index.dart';
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

class PayWidget extends StatefulWidget {
  const PayWidget({
    super.key,
    this.instance,
    required this.onPaymentSuccess,
    required this.onPaymentFailed,
    this.transactionToken,
    this.transactionToCreate,
    this.environment,
    this.amount,
    this.currency,
    this.customer,
    this.description,
    this.mode,
    this.callbackUrl,
  });

  final FedaFlutter? instance;
  final VoidCallback onPaymentSuccess;
  final VoidCallback onPaymentFailed;

  /// A FedaPay transaction token generated by your backend.
  /// If provided, [instance] and [transactionToCreate] are ignored.
  final String? transactionToken;

  final TransactionCreate? transactionToCreate;
  final ApiEnvironment? environment;
  final int? amount;
  final CurrencyIso? currency;
  final Map<String, dynamic>? customer;
  final String? description;
  final String? mode;
  final String? callbackUrl;

  @override
  State<PayWidget> createState() => _PayWidgetState();
}

class _PayWidgetState extends State<PayWidget> {
  bool _isLoading = false;
  bool _isPolling = false;
  String? _currentPaymentUrl;
  int? _transactionId;
  Timer? _pollingTimer;

  @override
  void initState() {
    super.initState();
    _startPayment();
  }

  @override
  void dispose() {
    _pollingTimer?.cancel();
    super.dispose();
  }

  Future<void> _startPayment() async {
    setState(() {
      _isLoading = true;
      _isPolling = false;
    });
    _pollingTimer?.cancel();

    try {
      String? url;
      if (widget.transactionToken != null && widget.transactionToken!.isNotEmpty) {
        url = 'https://checkout.fedapay.com/pay/${widget.transactionToken}';
        // In this case, we don't have the ID, so we can't poll easily
        // unless we extract it or provide it.
      } else if (widget.instance != null) {
        final payload = widget.transactionToCreate ??
            TransactionCreate(
              description: widget.description ?? 'Payment',
              amount: widget.amount ?? 0,
              currency: widget.currency ?? CurrencyIso(iso: 'XOF'),
              callbackUrl: widget.callbackUrl,
              customMetadata: null,
              customer: widget.customer,
            );
        final res = await widget.instance!.transactions.createTransaction(payload);
        if (res.isSuccessful && res.data != null) {
          _transactionId = res.data!.id;
          url = res.data!.paymentUrl;
          if (url == null && res.data!.paymentToken != null) {
            url = 'https://checkout.fedapay.com/pay/${res.data!.paymentToken}';
          }
        }
      }

      if (url != null) {
        _currentPaymentUrl = url;
        final uri = Uri.parse(url);
        if (await canLaunchUrl(uri)) {
          await launchUrl(uri, mode: LaunchMode.externalApplication);
          if (_transactionId != null) {
            _startPolling();
          }
        } else {
          widget.onPaymentFailed();
        }
      } else {
        widget.onPaymentFailed();
      }
    } catch (e) {
      debugPrint('PayWidget error: $e');
      widget.onPaymentFailed();
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  void _startPolling() {
    if (_transactionId == null || widget.instance == null) return;
    
    setState(() => _isPolling = true);
    _pollingTimer = Timer.periodic(const Duration(seconds: 3), (timer) async {
      try {
        final res = await widget.instance!.transactions.getTransaction(_transactionId!);
        if (res.isSuccessful && res.data != null) {
          final status = res.data!.status?.toLowerCase();
          if (status == 'approved' || status == 'transferred') {
            timer.cancel();
            if (mounted) {
              setState(() => _isPolling = false);
              widget.onPaymentSuccess();
            }
          } else if (status == 'canceled' || status == 'declined') {
            timer.cancel();
            if (mounted) {
              setState(() => _isPolling = false);
              widget.onPaymentFailed();
            }
          }
        }
      } catch (e) {
        debugPrint('Polling error: $e');
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    final hasFailed = _currentPaymentUrl == null && !_isLoading;
    return Center(
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          Icon(
            hasFailed ? Icons.error_outline : (_isPolling ? Icons.sync : Icons.payment),
            size: 64,
            color: hasFailed ? Colors.red : Colors.blue,
          ),
          const SizedBox(height: 16),
          Text(
            hasFailed
                ? 'La création du paiement a échoué.'
                : (_isPolling 
                    ? 'Paiement en cours... En attente de validation.' 
                    : 'Effectuez votre paiement dans le navigateur'),
            textAlign: TextAlign.center,
          ),
          if (_isPolling) ...[
            const SizedBox(height: 24),
            const CircularProgressIndicator(),
            const SizedBox(height: 24),
            const Text(
              'Ne fermez pas cette fenêtre après avoir payé.\nL\'application se mettra à jour automatiquement.',
              textAlign: TextAlign.center,
              style: TextStyle(fontSize: 12, color: Colors.grey),
            ),
          ],
          const SizedBox(height: 24),
          ElevatedButton(
            onPressed: (_isLoading || _isPolling) ? null : _startPayment,
            child: _isLoading
                ? const SizedBox(
                    height: 20,
                    width: 20,
                    child: CircularProgressIndicator(strokeWidth: 2),
                  )
                : Text(
                    hasFailed ? 'Réessayer' : (_isPolling ? 'En attente...' : 'Relancer le paiement'),
                  ),
          ),
        ],
      ),
    );
  }
}
