import 'dart:io';
import 'package:feda_flutter/src/exports/index.dart';
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';
import 'package:url_launcher/url_launcher.dart';

class PayWidget extends StatefulWidget {
  const PayWidget({
    super.key,
    this.instance,
    required this.onPaymentSuccess,
    required this.onPaymentFailed,
    this.transactionToken,
    this.transactionToCreate,
    this.environment,
    this.amount,
    this.currency,
    this.customer,
    this.description,
    this.mode,
    this.callbackUrl,
  });

  final FedaFlutter? instance;
  final VoidCallback onPaymentSuccess;
  final VoidCallback onPaymentFailed;

  /// A FedaPay transaction token generated by your backend.
  /// If provided, [instance] and [transactionToCreate] are ignored.
  final String? transactionToken;

  final TransactionCreate? transactionToCreate;
  final ApiEnvironment? environment;
  final int? amount;
  final CurrencyIso? currency;
  final Map<String, dynamic>? customer;
  final String? description;
  final String? mode;
  final String? callbackUrl;

  static const List<String> _allowedPaymentDomains = [
    'checkout.fedapay.com',
    'fedapay.com',
  ];

  static bool _isAllowedDomain(String host) {
    final hostLower = host.toLowerCase();
    for (final domain in _allowedPaymentDomains) {
      if (hostLower == domain || hostLower.endsWith('.$domain')) {
        return true;
      }
    }
    return false;
  }

  @override
  State<PayWidget> createState() => _PayWidgetState();
}

class _PayWidgetState extends State<PayWidget> {
  bool _isLoading = false;
  WebViewController? _controller;
  String? _currentPaymentUrl;

  @override
  void initState() {
    super.initState();

    if (Platform.isAndroid || Platform.isIOS) {
      _controller = WebViewController()
        ..setJavaScriptMode(JavaScriptMode.unrestricted)
        ..setNavigationDelegate(
          NavigationDelegate(
            onNavigationRequest: (request) {
              final uri = Uri.tryParse(request.url);
              if (uri != null && uri.host.isNotEmpty) {
                if (!PayWidget._isAllowedDomain(uri.host)) {
                  debugPrint("Navigation blocked: ${uri.host}");
                  return NavigationDecision.prevent;
                }
              }
              return NavigationDecision.navigate;
            },
            onUrlChange: (change) {
              if (change.url != null) {
                final uri = Uri.tryParse(change.url!);
                if (uri != null) {
                  if (uri.path.endsWith('/status/success')) {
                    widget.onPaymentSuccess();
                  } else if (uri.path.endsWith('/status/failure')) {
                    widget.onPaymentFailed();
                  }
                }
              }
            },
          ),
        );
    }

    _startPayment();
  }

  Future<void> _startPayment() async {
    setState(() => _isLoading = true);
    try {
      String? url;
      if (widget.transactionToken != null && widget.transactionToken!.isNotEmpty) {
        url = 'https://checkout.fedapay.com/pay/${widget.transactionToken}';
      } else if (widget.instance != null) {
        final payload = widget.transactionToCreate ??
            TransactionCreate(
              description: widget.description ?? 'Payment',
              amount: widget.amount ?? 0,
              currency: widget.currency ?? CurrencyIso(iso: 'XOF'),
              callbackUrl: widget.callbackUrl,
              customMetadata: null,
              customer: widget.customer,
            );
        final res = await widget.instance!.transactions.createTransaction(payload);
        if (res.isSuccessful && res.data != null) {
          url = res.data!.paymentUrl;
          if (url == null && res.data!.paymentToken != null) {
            url = 'https://checkout.fedapay.com/pay/${res.data!.paymentToken}';
          }
        }
      }

      if (url != null) {
        _currentPaymentUrl = url;
        if (_controller != null) {
          await _controller!.loadRequest(Uri.parse(url));
        } else {
          // Fallback for non-mobile platforms (Desktop)
          final uri = Uri.parse(url);
          if (await canLaunchUrl(uri)) {
            await launchUrl(uri, mode: LaunchMode.externalApplication);
          } else {
            widget.onPaymentFailed();
          }
        }
      } else {
        widget.onPaymentFailed();
      }
    } catch (e) {
      debugPrint('PayWidget error: $e');
      widget.onPaymentFailed();
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    if (_controller == null) {
      final hasFailed = _currentPaymentUrl == null && !_isLoading;
      return Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(
              hasFailed ? Icons.error_outline : Icons.computer,
              size: 64,
              color: hasFailed ? Colors.red : Colors.grey,
            ),
            const SizedBox(height: 16),
            Text(
              hasFailed
                  ? 'La création du paiement a échoué.'
                  : 'Utilisez le bouton ci-dessous pour payer :',
            ),
            const SizedBox(height: 24),
            ElevatedButton(
              onPressed: _isLoading ? null : _startPayment,
              child: _isLoading
                  ? const SizedBox(
                      height: 20,
                      width: 20,
                      child: CircularProgressIndicator(strokeWidth: 2),
                    )
                  : Text(
                      hasFailed ? 'Réessayer' : 'Ouvrir dans le navigateur',
                    ),
            ),
          ],
        ),
      );
    }

    return _isLoading
        ? const Center(child: CircularProgressIndicator())
        : WebViewWidget(controller: _controller!);
  }
}
