<script setup lang="ts">
const { data: page } = await useAsyncData('index', () => queryCollection('landing').path('/').first())
if (!page.value) {
  throw createError({ statusCode: 404, statusMessage: 'Page not found', fatal: true })
}

const title = page.value.seo?.title || page.value.title
const description = page.value.seo?.description || page.value.description

useSeoMeta({
  titleTemplate: '',
  title,
  ogTitle: title,
  description,
  ogDescription: description
})

// OG image generated by nuxt-og-image using the OgImageDocs component
defineOgImageComponent('Docs', {
  title: 'feda_flutter',
  description: 'A Dart/Flutter SDK to integrate FedaPay payments.',
  headline: 'Documentation'
})

// JSON-LD structured data for the software library
useHead({
  script: [{
    type: 'application/ld+json',
    innerHTML: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareSourceCode',
      name: 'feda_flutter',
      description: 'A Dart/Flutter package to integrate FedaPay payments.',
      url: 'https://feda-flutter.pages.dev',
      codeRepository: 'https://github.com/Blasterx7/feda_flutter',
      programmingLanguage: 'Dart',
      license: 'https://github.com/Blasterx7/feda_flutter/blob/main/LICENSE',
      author: {
        '@type': 'Person',
        name: 'Blasterx7',
        url: 'https://github.com/Blasterx7'
      }
    })
  }]
})
</script>

<template>
  <ContentRenderer
    v-if="page"
    :value="page"
    :prose="false"
  />
</template>

